export const EntryFieldConfig: Record<string, string[]> = {
  contact: [
    'phoneNumber',
    'email',
    'linkedInAccount',
    'gitHubAccount',
    'instagramAccount',
    'facebookAccount',
    'cityOfResidence',
    'zipCode',
  ],
  education: [
    'title',
    'trainingCenter',
    'graduationYear',
    'comments',
    'cloudDocumentName',
    'documentCloudMetadata',
  ],
  experience: [
    'position',
    'nameCompany',
    'startDate',
    'endDate',
    'description',
    'keywords',
    'nameLink',
    'linkUrl',
    'cloudDocumentName',
    'documentCloudMetadata',
  ],

  identity: ['names', 'lastNames'],
  language: ['name', 'level', 'cloudDocumentName', 'documentCloudMetadata'],
  portfolio: ['projectName', 'projectUrl'],
  profession: ['generalTitle', 'specificTitle'],
  profilePicture: ['urlPicture', 'shape'],
  softSkill: ['keyWords'],
  summary: ['title', 'text'],
  technicalSkill: ['keyWords'],
};

export const EntryRestrictedTypes = [
  'contact',
  'identity',
  'profession',
  'profilePicture',
  'summary',
];
export const EntryContainerTypes = [
  'contact',
  'identity',
  'profession',
  'profilePicture',
  'summary',
  'listEducation',
  'listExperience',
  'listSoftSkill',
  'listTechicalSkill',
  'listLanguage',
  'listPortfolio',
];
